name: {{ cookiecutter.env_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{ cookiecutter.python_version }}
  - awscli
  - black
  - click
  - coverage
  - flake8
  - nb_conda_kernels
  - pip
  - python-dotenv
  - sphinx
  - pip:
    - -e .
